include:
  - project: kit/cm/teaching/engineeringknowledge/cicd/pipeline
    ref: "1"
    file : base.yaml
  - project: kit/cm/teaching/engineeringknowledge/cicd/pipeline
    ref: "1"
    file : image.yaml
  - project: kit/cm/teaching/engineeringknowledge/cicd/pipeline
    ref: "1"
    file : go.yaml
variables:
  DEV_ACCOUNT: uabcd