# Note that the prefix in the npm commands forces npm to use the src folder.
include:
  - project: kit/cm/teaching/engineeringknowledge/cicd/pipeline
    ref: "1"
    file : base.yaml
  - project: kit/cm/teaching/engineeringknowledge/cicd/pipeline
    ref: "1"
    file : image.yaml
  - project: kit/cm/teaching/engineeringknowledge/cicd/pipeline
    ref: "golang-src-folder"
    file : go.yaml